Python Version Check

In [3]:
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [4]:
myList = [1, 2, 3]
print("Original List:", myList)

Original List: [1, 2, 3]


In [5]:
myList.append(4)
print("After appending: ", myList)

After appending:  [1, 2, 3, 4]


In [6]:
myTuple = (1, 2, 3)
print("Original Tuple:", myTuple)


Original Tuple: (1, 2, 3)


In [7]:
# myTuple.append(4) # Tuple is immutable

In [8]:
age = 21
pi = 3.14
temperature = -5.5
print("Data type of variable age is ", type(age))
print("Data type of variable pi is ", type(pi))
print("Data type of variable temperature is ", type(temperature))

Data type of variable age is  <class 'int'>
Data type of variable pi is  <class 'float'>
Data type of variable temperature is  <class 'float'>


In [9]:
name = "Alice"
greeting = "Hello"
address = "123 Main St"

print("Data Type of the variable name: ", type(name))
print("Data type of the var greeting: ", type(greeting))
print("Data type of the variable address: ", type(address))

Data Type of the variable name:  <class 'str'>
Data type of the var greeting:  <class 'str'>
Data type of the variable address:  <class 'str'>


In [10]:
print("The first letter of the name is: ", name[0])
print("The last letter of the name is ", name[-1])

The first letter of the name is:  A
The last letter of the name is  e


In [11]:
print("The second letter to the fourth of the name is ", name[1:4])
print("The first two letters of the name are: ", name[:2])
print("The letters from the 2nd to the end: ", name[1:])

The second letter to the fourth of the name is  lic
The first two letters of the name are:  Al
The letters from the 2nd to the end:  lice


In [12]:
list1 = [1, 2, 3, 4]
mixedList = [12, "Hello", True]

mixedList[0] = False
print(mixedList)

[False, 'Hello', True]


In [13]:
while True:
  operation = input("Enter the type of conversion (length, weight, volume): ")
  if operation == "length":
    value = input("Enter the value: ")
    while True:
      lengthOper = input("Enter the type of conversion (metre to feet(1), feet to metre(2)): ")
      if lengthOper == "1":
        print(f"The value {float(value)} in feet is: {float(value) * 3.28}")
        break
      elif lengthOper == "2":
        print(f"The value {float(value)} in metres is: {float(value) / 3.28}")
        break
      else:
        print("Invalid operation. Please enter between 1 and 2:")
    break
  elif operation == "weight" or operation == "Weight":
    value = input("Enter the value: ")
    while True:
      weightOper = input("Enter the type of conversion (kgs to pounds(1), pounds to kgs(2)): ")
      if weightOper == "1":
        print(f"The value {float(value)} in pounds is: {float(value) * 2.205} lbs")
        break
      elif weightOper == "2":
        print(f"The value {float(value)} in kgs is: {float(value) / 2.205} kgs")
        break
      else:
        print("Invalid operation. Please enter between 1 and 2:")
    break
  elif operation == "Volume" or operation == "volume":
    value = input("Enter the value: ")
    while True:
      oper = input("Enter the type of conversion (liters to gallons(1), gallons to liters(2)): ")
      if oper == "1":
        print(f"The value {float(value)} in gallons is: {float(value) /3.78} gals")
        break
      elif oper == "2":
        print(f"The value {float(value)} in liters is: {float(value) * 3.78} ltrs")
        break
      else:
        print("Invalid operation. Please enter between 1 and 2:")
    break




Enter the type of conversion (length, weight, volume): length
Enter the value: 20
Enter the type of conversion (metre to feet(1), feet to metre(2)): 1
The value 20.0 in feet is: 65.6


In [14]:
def sumList(numList):
  print(f"The sum of the list is: {sum(numList)}")

def averageList(numList):
  print(f"The average of the list is: {sum(numList) / len(numList)}")

def maxList(numList):
  print(f"The max of the list is: {max(numList)}")

def minList(numList):
  print(f"The min of the list is: {min(numList)}")

def main():
    try:
        print("Choose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter your choice (1-4): ")

        numbers_input = input("Enter numbers separated by spaces: ")

        # Convert input string to list of floats
        numbers = [float(num) for num in numbers_input.split()]

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == "1":
          sumList(numbers)

        elif choice == "2":
          averageList(numbers)

        elif choice == "3":
          maxList(numbers)
        elif choice == "4":
          minList(numbers)

        else:
            print("Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numbers separated by spaces.")


# Run the program
main()



Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 1 2 3 4
The average of the list is: 2.5


In [15]:
def extract_every_other(lst):
  return lst[::2]

lst=[2,4,6,7,9,1]
print(extract_every_other(lst))

[2, 6, 9]


In [16]:
def reverse_list(lst):
  return lst[::-1]

lst=[2,4,6,7,9,1]
reverse_list(lst)

[1, 9, 7, 6, 4, 2]

In [17]:
def remove_first_last(lst):
  return lst[1:-1]

lst=[2,4,6,7,9,1]
remove_first_last(lst)

[4, 6, 7, 9]

In [18]:
def get_first_n(lst, n):
  return lst[:n]

lst=[2,4,6,7,9,1]
get_first_n(lst, 3)

[2, 4, 6]

In [19]:
def getLast_n(lst, n):
  return lst[-n::]

lst=[2,4,6,7,9,1]
getLast_n(lst, 3)

[7, 9, 1]

In [20]:
def reverse_skip(lst):
  return lst[-2::-2]


# call the function
lst=[1,2,3,4,5,6]
reverse_skip(lst)

[5, 3, 1]

In [21]:
def flatten(lst): return [x for sub in lst for x in sub]

myList = [[1, 2], [3, 4], [5, 6]]
flatten(myList)

[1, 2, 3, 4, 5, 6]

In [22]:
def access_nested_element(lst, indices):
    for i in indices:
        lst = lst[i]
    return lst

access_nested_element([1, [2, [3, 4], 5], 6], [1, 1, 0])

3

In [23]:
def sum_nested(lst):
  sum = 0
  for i in lst:
    if isinstance(i, list):
      sum += sum_nested(i)
    else:
      sum += i
  return sum

print(sum_nested([[1, 2], [3, [4, 5]], 6],))

21


In [24]:
def remove_ele(lst, n):
  result = []

  for i in lst:
    if i == n:
      continue

    if isinstance(i, list):
      result.append(remove_ele(i, n))
    else:
      result.append(i)

  return result


print(remove_ele([[1, 2], [3, [4, 5]], 6], 6))

[[1, 2], [3, [4, 5]]]


In [25]:
def find_max(lst):
    maxNum = float('-inf')  # works with negative numbers

    for i in lst:
        if isinstance(i, list):
            returnedVal = find_max(i)
            if returnedVal > maxNum:
                maxNum = returnedVal
        else:
            if i > maxNum:
                maxNum = i

    return maxNum

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


In [26]:
def count_occurences(lst, elem):
  sum = 0
  for i in lst:
    if isinstance(i, list):
      sum += count_occurences(i, elem)
    else:
      if i == elem:
        sum += 1
  return sum

count_occurences([[1, 2], [2, 3], [2, 4]], 2)


3

In [27]:
def deep_flatten(lst):
  newList = []
  for i in lst:
    if isinstance(i, list):
      newList.extend(deep_flatten(i))
    else:
      newList.append(i)
  return newList

deep_flatten([[1, 2], [3, [4, 5]], 6])

[1, 2, 3, 4, 5, 6]

In [28]:
def average_nested(lst):
  newList = []
  for i in lst:
    if isinstance(i, list):
      newList.extend(deep_flatten(i))
    else:
      newList.append(i)
    return newList

average_nested([[1, 2], [3, [4, 5]], 6])


[1, 2]

In [39]:
emptyArr = np.empty((2,2))
onesArr = np.ones((4,2))
zerosArr = np.full((3, 3), 5, dtype=float) # creting a 3X3 array, containing 5 as its values in float

print(f"{emptyArr}\n")
print(f"{onesArr}\n")
print(f"{zerosArr}\n")

[[9.4182924e-316 0.0000000e+000]
 [4.9900630e-322 5.7845917e-317]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]



In [40]:
zerosLikeArr = np.zeros_like(onesArr) # creating an array of same shape as onesArr's but filled with 0

print(zerosLikeArr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [41]:
onesLikeArr = np.ones_like(zerosArr) # creating an array of same shape as zerosArr's but filled with 1

print(onesLikeArr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
newList = [1, 2, 3, 4]
arr = np.array(newList)
print(arr)
print(arr.shape) # shape is only valid with array but not python lists

[1 2 3 4]
(4,)


**Problem 2**

In [46]:
# Creating an array ranging from 10 to 49
rangedArr = np.arange(10, 49, 1)
print(rangedArr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [48]:
# Creating an array containing 9 elements ranging from 0 to 9. Furthermore rearranging the array to 3X3 array
arr = np.arange(9).reshape((3, 3))

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
# Creating 3X3 identity matrix
identityMatrix = np.eye(3) # Since Identity matrix are square matrices, a single shape's component can define the shape of matrices

print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)

# Calculate the mean of the array
array_mean = random_array.mean()

print(f"Array: \n{random_array}\n")
print(f"* * * * * * * * * * * * * * * \n\nMean: {array_mean}")

Array: 
[0.14017384 0.98490242 0.7740857  0.83443733 0.397575   0.23037868
 0.67156754 0.22563534 0.32251196 0.81701827 0.93381718 0.8944031
 0.83824134 0.19851467 0.87720698 0.24244377 0.20425495 0.49028878
 0.47203899 0.28139735 0.17105027 0.67184229 0.0420254  0.61424477
 0.74905332 0.26774866 0.63076106 0.70661705 0.75312087 0.12125148]

* * * * * * * * * * * * * * * 

Mean: 0.5186202782668569


In [55]:
# Create a 10x10 array with random values between 0 and 1
array_2d = np.random.random((10, 10))

# Find the minimum and maximum values
z_min = array_2d.min()
z_max = array_2d.max()

print(f"Minimum Value: {z_min}")
print(f"Maximum Value: {z_max}")

Minimum Value: 0.015110075314508808
Maximum Value: 0.9831307625011465


In [56]:
# Create a zero array of size 10
z_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
z_array[4] = 1

print(z_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [58]:
arr = [1,2,0,0,4,0]
actualArr = np.array(arr)

reversedArr = actualArr[::-1]
print(reversedArr)

[0 4 0 0 2 1]


In [59]:
# Define the shape (e.g., 5x5)
z = np.ones((5, 5))

# Use slicing to fill the interior (from index 1 to the second-to-last as the stop point is excluded) with 0
z[1:-1, 1:-1] = 0

print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
# Create an 8x8 array of zeros
z = np.zeros((8, 8), dtype=int)

# Fill with 1s using stepping [start:stop:step]
z[1::2, ::2] = 1  # Even columns in odd rows
z[::2, 1::2] = 1  # Odd columns in even rows

print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [62]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

In [64]:
add_xy = x + y
sub_xy = x - y
mult_x = x * 3
sq_x = x**2

print(add_xy)
print(sub_xy)
print(mult_x)
print(sq_x)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]


In [66]:
v = np.array([9,10])
w = np.array([11,12])

# Dot product v and w
dot_vw = np.dot(v, w)

# Dot product x and v
dot_xv = np.dot(x, v)

# Dot product x and y
dot_xy = np.dot(x, y)

print(dot_vw)
print(dot_xv)
print(dot_xy)

219
[29 77]
[[19 22]
 [50 58]]


In [67]:
concat_xy = np.vstack((x, y))
concat_vw = np.column_stack((v, w))

print(concat_xy)
print(concat_vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [68]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A_inv:\n", np.round(I)) # Rounding to handle floating point precision

A * A_inv:
 [[1. 0.]
 [0. 1.]]


In [69]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))


Is AB equal to BA? False


In [70]:
lhs = (np.dot(A, B)).T
rhs = np.dot(B.T, A.T)
print("\nIs (AB).T == B.T @ A.T?", np.allclose(lhs, rhs))


Is (AB).T == B.T @ A.T? True


In [71]:
A_sys = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

A_inv_sys = np.linalg.inv(A_sys)
X = np.dot(A_inv_sys, B_sys)

print(f"\nSolution (x, y, z): {X}")


Solution (x, y, z): [ 2.  1. -2.]


In [72]:
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

In [73]:
start = time.time()
res_list = [x + y for x, y in zip(list1, list2)]
print(f"List Addition: {time.time() - start:.5f}s")

List Addition: 0.07046s


In [74]:
start = time.time()
res_arr = arr1 + arr2
print(f"NumPy Addition: {time.time() - start:.5f}s")

NumPy Addition: 0.00554s


In [75]:
start = time.time()
dot_list = sum(x * y for x, y in zip(list1, list2))
print(f"List Dot Product: {time.time() - start:.5f}s")

List Dot Product: 0.16988s


In [76]:
start = time.time()
dot_arr = np.dot(arr1, arr2)
print(f"NumPy Dot Product: {time.time() - start:.5f}s")

NumPy Dot Product: 0.00227s
